export const svgs = {
  shoes: `<i class="fa-solid fa-shoe-prints text-3xl"></i>`,
  head: `<i class="fa-solid fa-hard-hat text-3xl"></i>`,
  eye: `<i class="fa-solid fa-glasses text-3xl"></i>`,
  gloves: `<i class="fa-solid fa-mitten text-3xl"></i>`,
  body: `<i class="fa-solid fa-user-shield text-3xl"></i>`,
  hearing: `<i class="fa-solid fa-headphones text-3xl"></i>`,
  welding: `<i class="fa-solid fa-mask text-3xl"></i>`,
  fall: `<i class="fa-solid fa-link text-3xl"></i>`,
  vest: `<i class="fa-solid fa-vest text-3xl"></i>`,
};

export const benefitDict = {
  headComfort: { icon: 'fa-cloud', label: 'Comfort', desc: 'ABS to keep helmet lightweight and comfortable. Features 3 textile straps with 8 attachment points for optimal weight distribution. Adjustable headband can be positioned high or low for better fit and comfort. Adjustable from 53cm to 63cm for optimized comfort.' },
  headHygiene: { icon: 'fa-hands-bubbles', label: 'Hygiene', desc: 'Replaceable headband for a better hygiene. Removable brow pad washable and replaceable for a perfect hygiene solution.' },
  headPerformance: { icon: 'fa-chart-line', label: 'Performance', desc: 'Adjustable headband can be positioned high or low for a secure fit that keeps helmet in place during movement.' },
  headDurability: { icon: 'fa-hourglass-half', label: 'Durability', desc: 'Replacement basane.' },
  headEaseOfUse: { icon: 'fa-hand-pointer', label: 'Ease of Use', desc: 'Reverse wearing for a maximum field of vision without visor.' },
  hygiene: { icon: 'fa-hands-bubbles', label: 'Hygiene', desc: 'Reduces perspiration thanks to its excellent breathability. Nitrile means no risk of allergies for users' },
  performance: { icon: 'fa-chart-line', label: 'Performance', desc: 'Lightweight for optimal dexterity. Nitrile coating gives excellent grip in oily/greasy environments. SOFTnocut fiber provides excellent cut resistance' },
  durability: { icon: 'fa-shield-halved', label: 'Durability', desc: 'High-quality coating extends the life of the glove and provides excellent protection for the hand' },
  performance1: { icon: 'fa-chart-line', label: 'Performance', desc: 'Lightweight for optimal dexterity' },
  radiantHeatShield: { icon: 'fa-fire-flame-curved', label: 'Radiant Heat Shield', desc: 'Aluminised back and cuff reflect extreme radiant heat for maximum protection during welding' },
  highDurability: { icon: 'fa-shield-halved', label: 'High Durability', desc: 'Premium split leather construction with para-aramid stitching ensures long-lasting mechanical resistance' },
  chemicalProtection: { icon: 'fa-shield-halved', label: 'Chemical Protection', desc: 'Type 5B/6B rated protection against dry particles and limited liquid splash' },
  antiStatic: { icon: 'fa-bolt', label: 'Anti-Static', desc: 'EN 1149-5 certified anti-static properties for hazardous environments' },
  waterproof: { icon: 'fa-droplet', label: 'Waterproof', desc: 'Type 3B rated total waterproofing with taped seams for maximum liquid protection' },
  antiStatic1: { icon: 'fa-bolt', label: 'Anti-Static', desc: 'EN 1149-5 certified anti-static for explosive atmosphere environments' },
  sustainability: { icon: 'fa-recycle', label: 'Sustainability', desc: 'Replacement cushions available to extend life of the product' },
  hygiene1: { icon: 'fa-hands-bubbles', label: 'Hygiene', desc: 'Washable reusable for weeks without losing attenuation' },
  comfort: { icon: 'fa-cloud', label: 'Comfort', desc: 'Double headband for greater flexibility and comfort' },
  performance2: { icon: 'fa-chart-line', label: 'Performance', desc: 'High-performance multi-hull attenuation technology' },
  compact: { icon: 'fa-compress', label: 'Compact', desc: 'Foldable headband for less space and easier storage' },
  hygiene2: { icon: 'fa-hands-bubbles', label: 'Hygiene', desc: 'Replaceable cushions — perfect hygiene kit solution' },
  easyToUse: { icon: 'fa-hand-pointer', label: 'Easy to Use', desc: 'Built-in firm handle directs insertion angle for better fit' },
  comfort1: { icon: 'fa-cloud', label: 'Comfort', desc: 'Contoured 3 flange polymer design provides all-day comfort' },
  performance3: { icon: 'fa-chart-line', label: 'Performance', desc: 'Ultra-soft polymer for superior SNR 34dB attenuation' },
  hygiene3: { icon: 'fa-hands-bubbles', label: 'Hygiene', desc: 'Firm handle allows hygienic insertion without touching the plug body' },
  comfort2: { icon: 'fa-cloud', label: 'Comfort', desc: 'Low pressure pads minimize clamping force for all-day wear' },
  adjustability: { icon: 'fa-sliders', label: 'Adjustability', desc: 'Adjustable headband ensures a secure personalized fit' },
  easyToUse1: { icon: 'fa-hand-pointer', label: 'Easy to Use', desc: 'Built-in firm handle for correct angle of insertion' },
  performance4: { icon: 'fa-chart-line', label: 'Performance', desc: 'Ultra-soft polymer for superior attenuation' },
  zirconComfort: { icon: 'fa-cloud', label: 'Comfort', desc: 'Adjustable from 53cm to 63cm for optimized comfort' },
  zirconHygiene: { icon: 'fa-hands-bubbles', label: 'Hygiene', desc: 'Replaceable headband for a better hygiene. Replaceable suspension for a better hygiene. Removable brow pad washable and replaceable for a perfect hygiene solution.' },
  graniteComfort: { icon: 'fa-cloud', label: 'Comfort', desc: 'Breathability of vented helmet makes extended wear comfortable. ABS to keep helmet lightweight and comfortable. Features 3 textile straps with 8 attachment points for optimal weight distribution. Adjustable headband can be positioned high or low for better fit and comfort. Adjustable from 53cm to 63cm for optimized comfort. Lack of visor improves field of vision.' },
  graniteHygiene: { icon: 'fa-hands-bubbles', label: 'Hygiene', desc: 'Replaceable suspension for a better hygiene. Removable brow pad washable and replaceable for a perfect hygiene solution.' },
  forestierComfort: { icon: 'fa-cloud', label: 'Comfort', desc: 'Features 3 textile straps with 8 attachment points for optimal weight distribution. Adjustable headband can be positioned high or low for better fit and comfort. Adjustable from 53cm to 63cm for optimized comfort.' },
  forestierCompatibility: { icon: 'fa-puzzle-piece', label: 'Compatibility', desc: 'Compatible with safety glasses. Compatible with noise-canceling headphones.' },
  forestierHygiene: { icon: 'fa-hands-bubbles', label: 'Hygiene', desc: 'Replaceable headband for a better hygiene. Replaceable suspension for a better hygiene. Removable brow pad washable and replaceable for a perfect hygiene solution.' },
};

export const certDict = {
  en388: { name: 'EN 388', details: 'Mechanical Risks Protection' },
  ansiIsea1052024: { name: 'ANSI/ISEA 105-2024', details: 'Hand Protection Standard' },
  en3881: { name: 'EN 388', details: '1 0 1 0 X' },
  enIso3741: { name: 'EN ISO 374-1', details: 'Type A AKLMNPT' },
  enIso3745: { name: 'EN ISO 374-5', details: 'Micro-organisms Protection' },
  foodContact: { name: 'Food Contact', details: 'Suitable for food handling' },
  en407: { name: 'EN 407', details: 'Thermal Risks Protection' },
  en3882: { name: 'EN 388', details: '3 2 3 4 X' },
  en4071: { name: 'EN 407', details: '4 1 2 4 4 4' },
  en12477: { name: 'EN 12477', details: 'Type A Welder Protective' },
  en374: { name: 'EN 374', details: 'Chemical Protection' },
  enIso139821: { name: 'EN ISO 13982-1', details: 'Type 5 Dry Particle Protection' },
  en13034: { name: 'EN 13034', details: 'Type 6 Limited Liquid Splash' },
  en14126: { name: 'EN 14126', details: 'Biological Hazards Protection' },
  en11495: { name: 'EN 1149-5', details: 'Anti-Static Properties' },
  en10732: { name: 'EN 1073-2', details: 'Radioactive Contamination' },
  en14605: { name: 'EN 14605', details: 'Type 3B/4B Liquid Tight' },
  en130341: { name: 'EN 13034', details: 'Type 6 Limited Splash' },
  en141261: { name: 'EN 14126', details: 'Biological Hazards' },
  enIso13688: { name: 'EN ISO 13688', details: 'General Requirements' },
  ce: { name: 'CE', details: 'European Conformity' },
  en3521: { name: 'EN 352-1', details: 'Ear Muffs Standard' },
  ansiS319: { name: 'ANSI S3.19', details: 'NRR 26 dB' },
  ulArEn3521: { name: 'UL-AR EN352-1', details: 'Underwriters Laboratories Certified' },
  en3523: { name: 'EN 352-3', details: 'SNR 30 dB · Helmet Mounted Ear Muffs' },
  ansiS3191: { name: 'ANSI S3.19', details: 'Hearing Protection Standard' },
  en35211: { name: 'EN 352-1', details: 'SNR 30 dB · Ear Muffs Standard' },
  ansiS3192: { name: 'ANSI S3.19', details: 'NRR 25 dB' },
  en35231: { name: 'EN 352-3', details: 'Helmet Mounted Ear Muffs' },
  ansiS3193: { name: 'ANSI S3.19', details: 'NRR 21 dB' },
  en3522: { name: 'EN 352-2', details: 'SNR 34 dB · H 33 · M 32 · L 31 · ø 8-12 mm' },
  en35212: { name: 'EN 352-1', details: 'SNR 23 dB · Ear Muffs Standard' },
  en35221: { name: 'EN 352-2', details: 'Ear Plugs Standard' },
  en397: { name: 'EN397:2012', details: 'Protective helmets for industry' },
  en50365: { name: 'EN 50365', details: 'Electrically insulating helmets for use on low voltage installations' },
  ulArIram3620: { name: 'UL-AR IRAM 3620', details: 'Safety helmets' },
  en397Forestier: { name: 'EN397:2012', details: '-10°C +50°C · 440VAC' },
  en50365Forestier: { name: 'EN 50365', details: 'Class 0' },
  en3523Forestier: { name: 'EN 352-3', details: 'SNR: 24 dB · H: 27 · M: 21 · L: 14 (S/M/L)' },
  en1731: { name: 'EN 1731', details: 'F (Mesh face shield standard)' },
  en166: { name: 'EN 166', details: 'F (Eye protection)' },
};


export const getBenefits = (...keys) => keys.map(k => benefitDict[k]).filter(Boolean);
export const getCerts = (...keys) => keys.map(k => certDict[k]).filter(Boolean);


export const categories = [
  { id: 'shoes', label: 'Safety Shoes', count: 19, icon: svgs.shoes, desc: 'Slip-resistant, impact-proof industrial footwear equipped with advanced shock absorption and S3-rated protection.', color: '#27C291' },
  { id: 'head', label: 'Skull Protection', count: 8, icon: svgs.head, desc: 'High-density thermoplastic hard hats engineered to dissipate extreme kinetic energy from overhead impacts.', color: '#FFCC00' },
  { id: 'eye', label: 'Eye Protection', count: 8, icon: svgs.eye, desc: 'Anti-scratch, anti-fog polycarbonate eyewear and face shields providing panoramic visibility and UV resistance.', color: '#27C291' },
  { id: 'vest', label: 'Safety Vest', count: 0, icon: svgs.vest, desc: 'High-visibility vests with reflective strips for enhanced worker safety in low-light conditions.', color: '#FFCC00' },
  { id: 'gloves', label: 'Gloves', count: 10, icon: svgs.gloves, desc: 'Precision tactile gloves offering Level F cut resistance, robust chemical defense, and superior ergonomic dexterity.', color: '#27C291' },
  { id: 'hearing', label: 'Hearing Protection', count: 8, icon: svgs.hearing, desc: 'High-attenuation ear muffs and ergonomic earplugs designed to isolate and dampen sustained industrial decibel extremes.', color: '#27C291' },
  { id: 'body', label: 'Body Protection', count: 6, icon: svgs.body, desc: 'Microporous coveralls, thermal FR gear, and chemical suits certified to shield against hazardous particulate and splash.', color: '#1a9e76' },
  { id: 'welding', label: 'Welding', count: 5, icon: svgs.welding, desc: 'Auto-darkening active filters, split-leather aprons, and thermal barriers for optimal arc flash and spatter defense.', color: '#1a9e76' },
  { id: 'fall', label: 'Fall Protection', count: 6, icon: svgs.fall, desc: 'Multi-point full-body harnesses, energy-absorbing lanyards, and carabiners engineered for extreme vertical securement.', color: '#FFCC00' }
];

export const idToCat = {
  "13": "shoes",
  "14": "shoes",
  "15": "shoes",
  "16": "shoes",
  "17": "shoes",
  "18": "shoes",
  "19": "shoes",
  "20": "shoes",
  "21": "shoes",
  "22": "shoes",
  "23": "shoes",
  "100": "shoes",
  "101": "shoes",
  "102": "shoes",
  "103": "shoes",
  "104": "shoes",
  "105": "shoes",
  "106": "shoes",
  "107": "shoes",
  "200": "head",
  "201": "head",
  "202": "head",
  "203": "head",
  "204": "head",
  "205": "head",
  "206": "head",
  "207": "head",
  "300": "eye",
  "301": "eye",
  "302": "eye",
  "303": "eye",
  "304": "eye",
  "305": "eye",
  "306": "eye",
  "307": "eye",
  "400": "gloves",
  "401": "gloves",
  "402": "gloves",
  "403": "gloves",
  "404": "gloves",
  "405": "gloves",
  "406": "gloves",
  "407": "gloves",
  "408": "gloves",
  "409": "gloves",
  "500": "body",
  "501": "body",
  "502": "body",
  "503": "body",
  "504": "body",
  "505": "body",
  "600": "hearing",
  "601": "hearing",
  "602": "hearing",
  "603": "hearing",
  "604": "hearing",
  "605": "hearing",
  "606": "hearing",
  "607": "hearing",
  "700": "welding",
  "701": "welding",
  "702": "welding",
  "703": "welding",
  "704": "welding",
  "800": "fall",
  "801": "fall",
  "802": "fall",
  "803": "fall",
  "804": "fall",
  "805": "fall"
};

export const featuredProducts = [
  {
    id: 100,
    cat: 'shoes',
    name: 'JUMPER3 S1P SRC',
    brand: 'DeltaPlus',
    tags: ["S1P","SRC","Split Leather"],
    desc: 'Pigmented split leather safety shoe with S1P SRC rating. Designed for general industrial and manufacturing environments requiring basic impact and slip resistance.',
    features: ["Pigmented split leather upper","S1P safety rating","SRC slip resistance","Steel toecap","Anti-perforation midsole","Energy-absorbing heel"],
    benefits: [],
    certs: [],
    img: 'assets/products/shoes/jumper3-s1p-sr/thumbnail.png',
    images: ["assets/products/shoes/jumper3-s1p-sr/1.png","assets/products/shoes/jumper3-s1p-sr/2.png"],
    sizes: [4,5,6,6,7,8,9,10,11,11.5,12,13],
    colors: []
  },
  {
    id: 101,
    cat: 'shoes',
    name: 'MIAMI S2 SRC',
    brand: 'DeltaPlus',
    tags: ["S2","SRC","Microfibre"],
    desc: 'White microfibre low-cut safety shoe with S2 SRC rating. Ideal for food industry, pharmaceuticals, and clean manufacturing environments.',
    features: ["Microfibre upper — easy to clean","S2 safety rating","SRC slip resistance","Steel toecap","Water-resistant properties","Lightweight design"],
    benefits: [],
    certs: [],
    img: 'assets/products/shoes/miamis2-src/thumbnail.png',
    images: ["assets/products/shoes/miamis2-src/white/1.png","assets/products/shoes/miamis2-src/white/2.png"],
    sizes: [],
    colors: [{"name":"White","hex":"#fff","images":["assets/products/shoes/miamis2-src/white/1.png","assets/products/shoes/miamis2-src/white/2.png"]},{"name":"Black","hex":"#000","images":["assets/products/shoes/miamis2-src/black/1.png"]}]
  },
  {
    id: 102,
    cat: 'shoes',
    name: 'SUMMER S1P SRC',
    brand: 'DeltaPlus',
    tags: ["S1P","SRC","Polyester/Cotton"],
    desc: 'Breathable polyester and cotton safety shoe with S1P SRC rating. Designed for warm environments where ventilation and comfort are essential without compromising protection.',
    features: ["Polyester and cotton upper","S1P safety rating","SRC slip resistance","Composite toecap","Anti-perforation midsole","Breathable mesh lining"],
    benefits: [],
    certs: [],
    img: 'assets/products/shoes/summer-s1p-src/thumbnail.png',
    images: ["assets/products/shoes/summer-s1p-src/gray-orange/1.png","assets/products/shoes/summer-s1p-src/gray-orange/2.png"],
    sizes: [],
    colors: [{"name":"Gray-Orange","hex":"linear-gradient(225deg, #4b5563 50%, #fd7e14 50%)","images":["assets/products/shoes/summer-s1p-src/gray-orange/1.png","assets/products/shoes/summer-s1p-src/gray-orange/2.png"]},{"name":"Blue-Yellow","hex":"linear-gradient(225deg, #0d6efd 50%, #eab308 50%)","images":["assets/products/shoes/summer-s1p-src/blue-yellow/1.png"]}]
  },
  {
    id: 103,
    cat: 'shoes',
    name: 'SIMBA S3 SRC',
    brand: 'DeltaPlus',
    tags: ["S3","SRC","Buffalo Leather"],
    desc: 'Pigmented split buffalo leather high-cut safety boot with S3 SRC rating. Built for heavy construction, mining, and outdoor industrial applications requiring maximum protection.',
    features: ["Pigmented split buffalo leather upper","S3 safety rating","SRC slip resistance","Steel toecap","Anti-perforation steel midsole","Water-resistant (WR) construction"],
    benefits: [],
    certs: [],
    img: 'assets/products/shoes/simba-s3-src/thumbnail.png',
    images: ["assets/products/shoes/simba-s3-src/1.png","assets/products/shoes/simba-s3-src/2.png"],
    sizes: [4,5,6,6,7,8,9,10,11,11.5,12,13,14],
    colors: []
  },
  {
    id: 13,
    cat: 'shoes',
    name: 'MANILABOY S3',
    brand: 'Safety Jogger',
    tags: ["S3","SR","FO"],
    desc: 'SJPH Exclusive Item. Premium safety shoe featuring a Barton Action Leather upper and Recycled Mesh lining. Equipped with a robust Steel midsole and PU/PU outsole. Provides unparalleled protection with a Steel toecap and supreme comfort via the SJ Foam footbed. Rated S3 / SR, SC, LG, CI, FO.',
    features: ["Upper: Barton Action Leather","Lining: Recycled Mesh","Midsole: Steel","Outsole: PU/PU","Toecap: Steel","Footbed: SJ Foam","Norms: ASTM F2413:2018, EN ISO 20345:2022+A1:2024"],
    benefits: [],
    certs: [],
    img: 'assets/products/shoes/manilaboy_s3.png',
    images: [],
    sizes: [],
    colors: []
  },
  {
    id: 14,
    cat: 'shoes',
    name: 'BESTBOY MF EH',
    brand: 'Safety Jogger',
    tags: ["SB","EH","WPA"],
    desc: 'SJPH Exclusive Item. Electrical hazard protection shoe with Barton Action Leather upper and Recycled Mesh lining. Features an Anti Puncture Textile midsole and BASF PU/BASF PU outsole for advanced shock absorption. Fitted with a Composite toecap. Rated SB / PS, SR, SC, WPA, LG, E, CI, FO.',
    features: ["Upper: Barton Action Leather","Lining: Recycled Mesh","Midsole: Anti Puncture Textile","Outsole: BASF PU/BASF PU","Toecap: Composite","Footbed: SJ Foam","Norms: ASTM F2413:2018, EN ISO 20345:2022+A1:2024"],
    benefits: [],
    certs: [],
    img: 'assets/products/shoes/bestboy_mf_eh.png',
    images: [],
    sizes: [],
    colors: []
  },
  {
    id: 15,
    cat: 'shoes',
    name: 'MONTIS S3S',
    brand: 'Safety Jogger',
    tags: ["S3S","ESD","CI"],
    desc: 'SJPH Exclusive Item. Dark grey/silver safety shoe with Nubuck Action Leather upper and breathable Mesh lining. Anti Puncture Textile midsole and PU/PU outsole. Composite toecap. Rated S3S / SR, SC, LG, ESD, CI, FO.',
    features: ["Upper: Nubuck Action Leather","Lining: Mesh","Midsole: Anti Puncture Textile","Outsole: PU/PU","Toecap: Composite","Footbed: SJ Foam","Norms: ASTM F2413:2018, EN ISO 20345:2022"],
    benefits: [],
    certs: [],
    img: 'assets/products/shoes/montis_s3s.png',
    images: [],
    sizes: [],
    colors: []
  },
  {
    id: 16,
    cat: 'shoes',
    name: 'SAFETYBOY 2',
    brand: 'Safety Jogger',
    tags: ["S1P","SR","FO"],
    desc: 'SJPH Exclusive Item. Mid-cut safety boot with Barton Action Leather upper and Mesh lining. Steel midsole and PU outsole. Steel toecap with SJ Eco footbed. Rated S1 P / SR, FO.',
    features: ["Upper: Barton Action Leather","Lining: Mesh","Midsole: Steel","Outsole: PU","Toecap: Steel","Footbed: SJ Eco","Norms: ASTM F2413:2018, EN ISO 20345:2022"],
    benefits: [],
    certs: [],
    img: 'assets/products/shoes/safetyboy2.png',
    images: [],
    sizes: [],
    colors: []
  }
];

export const marqueeItems = categories.map(c => c.label);
